# Generated by Django 3.0.8 on 2020-07-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description_1', models.TextField()),
                ('description_2', models.TextField()),
                ('description_3', models.TextField()),
                ('description_4', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
