# Generated by Django 3.0.8 on 2020-08-27 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200827_0020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Condition',
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={},
        ),
        migrations.RenameField(
            model_name='store',
            old_name='category',
            new_name='condition',
        ),
    ]
